name: Android Release CI

on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        env:
          SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo $SIGNING_KEY_STORE_BASE64 | base64 --decode > ${{ github.workspace }}/release.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          SIGNING_KEY_STORE_PATH: ${{ github.workspace }}/release.keystore
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew :composeApp:assembleRelease

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: composeApp/build/outputs/apk/release/composeApp-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Android Apk to PGYER
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGYER_API_TOKEN }}
          appFilePath: composeApp/build/outputs/apk/release/composeApp-release.apk
